# Generated by Django 2.2.17 on 2020-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201212_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='a_choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='b_choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='c_choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='d_choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
